name: ParseableViewer
options:
  bundleIdPrefix: com.parseableviewer
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"
  createIntermediateGroups: true
  defaultConfig: Release

targets:
  ParseableViewer:
    type: application
    platform: macOS
    sources:
      - path: ParseableViewer
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.parseableviewer.app
        PRODUCT_NAME: "Parseable Viewer"
        PRODUCT_MODULE_NAME: ParseableViewer
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        COMBINE_HIDPI_IMAGES: YES
        INFOPLIST_FILE: ParseableViewer/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: "wholemodule"
    postBuildScripts:
      - script: |
          COMMIT_TIMESTAMP=$(TZ=UTC git log -1 --format='%cd' --date=format-local:'%Y%m%d.%H%M%S' 2>/dev/null)
          if [ -n "$COMMIT_TIMESTAMP" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${COMMIT_TIMESTAMP}" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${COMMIT_TIMESTAMP}" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          fi
        name: Set Version from Git Commit Timestamp
        basedOnDependencyAnalysis: false
    entitlements:
      path: ParseableViewer/ParseableViewer.entitlements

  ParseableViewerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ParseableViewerTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(BUILT_PRODUCTS_DIR)/Parseable Viewer.app/Contents/MacOS/Parseable Viewer"
        TEST_HOST: "$(BUNDLE_LOADER)"
    dependencies:
      - target: ParseableViewer

schemes:
  ParseableViewer:
    build:
      targets:
        ParseableViewer: all
        ParseableViewerTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ParseableViewerTests
    profile:
      config: Release
    analyze:
      config: Debug
